//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project4CSE445.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addPark", ReplyAction="http://tempuri.org/IService1/addParkResponse")]
        void addPark(string type, string name, string owner, string address, string addUrl, string neighbors, string date, string founder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addPark", ReplyAction="http://tempuri.org/IService1/addParkResponse")]
        System.Threading.Tasks.Task addParkAsync(string type, string name, string owner, string address, string addUrl, string neighbors, string date, string founder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/search", ReplyAction="http://tempuri.org/IService1/searchResponse")]
        string search(string url, string park);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/search", ReplyAction="http://tempuri.org/IService1/searchResponse")]
        System.Threading.Tasks.Task<string> searchAsync(string url, string park);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Project4CSE445.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Project4CSE445.ServiceReference1.IService1>, Project4CSE445.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void addPark(string type, string name, string owner, string address, string addUrl, string neighbors, string date, string founder) {
            base.Channel.addPark(type, name, owner, address, addUrl, neighbors, date, founder);
        }
        
        public System.Threading.Tasks.Task addParkAsync(string type, string name, string owner, string address, string addUrl, string neighbors, string date, string founder) {
            return base.Channel.addParkAsync(type, name, owner, address, addUrl, neighbors, date, founder);
        }
        
        public string search(string url, string park) {
            return base.Channel.search(url, park);
        }
        
        public System.Threading.Tasks.Task<string> searchAsync(string url, string park) {
            return base.Channel.searchAsync(url, park);
        }
    }
}
