//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberLoginPages.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/verifyMember", ReplyAction="http://tempuri.org/IService1/verifyMemberResponse")]
        bool verifyMember(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/verifyMember", ReplyAction="http://tempuri.org/IService1/verifyMemberResponse")]
        System.Threading.Tasks.Task<bool> verifyMemberAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/newMember", ReplyAction="http://tempuri.org/IService1/newMemberResponse")]
        string newMember(string username, string password, string confirmPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/newMember", ReplyAction="http://tempuri.org/IService1/newMemberResponse")]
        System.Threading.Tasks.Task<string> newMemberAsync(string username, string password, string confirmPassword);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : MemberLoginPages.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<MemberLoginPages.ServiceReference1.IService1>, MemberLoginPages.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool verifyMember(string username, string password) {
            return base.Channel.verifyMember(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> verifyMemberAsync(string username, string password) {
            return base.Channel.verifyMemberAsync(username, password);
        }
        
        public string newMember(string username, string password, string confirmPassword) {
            return base.Channel.newMember(username, password, confirmPassword);
        }
        
        public System.Threading.Tasks.Task<string> newMemberAsync(string username, string password, string confirmPassword) {
            return base.Channel.newMemberAsync(username, password, confirmPassword);
        }
    }
}
